# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: 'Contact'
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  image:
    url:
  logos:
    - light: images/github-mark.png
      dark: images/github-mark-white.png
    - light: images/linkedin-logo.png
      dark: images/linkedin-logo.png

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
