spec:
  structures:
    - content_blocks
  label: Welcome
  description: Welcome block
  icon: pan_tool
  tags: []

blueprint:
  heading:
  sub_heading:
  welcome_text:
  button: bookshop:generic/button

preview:
  heading: "Tom Richardson"
  sub_heading: "Solutions Architect"
  welcome_text: "I am a Solutions Architect for CloudCannon. At work, I craft solutions that help ease the transition to CloudCannon's CMS. Outside work, I am interested in creative web development and animations."
  button:
    _bookshop_name: generic/button
    button_link: "#contact"
    button_target: "_self"
    button_text: "Contact Me"

_inputs: {}
