# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Button"
  description: A button with link
  icon: smart_button
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  button_link:
  button_target:
  button_text:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  button_link: "#contact"
  button_target: "_self"
  button_text: "Contact Me"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  button_target:
    type: select
    options:
      hidden: "!button_link"
      values:
        - key: "_self"
          display_name: Same tab
        - key: "_blank"
          display_name: New tab
      value_key: key
      preview:
        text:
          - key: display_name
